<#
.SYNOPSIS
    An example script to restore permissions generated by running Send-As-Report script.
.DESCRIPTION
    The script uses the report to restore the permissions in Office 365.
		
.NOTES
    THIS CODE IS MADE AVAILABLE AS IS, WITHOUT WARRANTY OF ANY KIND. THE ENTIRE 
    RISK OF THE USE OR THE RESULTS FROM THE USE OF THIS CODE REMAINS WITH THE USER.    
#>
foreach ($entry in $csv)
{
Write-Output "Resolving delegate mail address..."
$TrusteeSamAccountName = $null
$TrusteeMail = $null
$TrusteeSamAccountName = $entry.SendAsDelegate.Split("\")[1]
$TrusteeObject = Get-ADObject -Filter {SamAccountName -eq $TrusteeSamAccountName} -Properties mail,userprincipalname
if ($TrusteeObject.ObjectClass -eq "user" ) {
$Trustee = $TrusteeObject.userprincipalname}
elseif ($TrusteeObject.ObjectClass -eq "group") {
$Trustee = $TrusteeObject.mail }
 
if ($Trustee) {
Write-Output "Adding recipient permission 'SendAs' for user or group $($Trustee) for $($entry.RecipientMail)"
Add-RecipientPermission $entry.RecipientMail -AccessRights SendAs -Trustee $Trustee -confirm:$false}
ELSE
{Write-Warning "Failed to resolve delegate"}
}